# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

install:
  - pip install -e .[dev]
  - pip install coveralls

script:
  - py.test --doctest-modules --cov=src/chbench src tests
after_success:
  - coveralls
