# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

install:
  - pip install -e .[dev]
  - pip install coveralls

script:
  - py.test --doctest-modules --cov=src/chbench tests
after_success:
  - coveralls
